### ISSUE TITLE
Test directory not found when running python build.py command 

### ISSUE THREAD

**Issue by turusko** [ShadityZ/Vitrix#22]
```
c:\source\Vitrix>python build.py

Build Path:        C:\source\Vitrix/build

------------------------------------------------------------------------------------------------------------------------

Preparing...

Done!

------------------------------------------------------------------------------------------------------------------------

Building...


C:
  from distutils.dir_util import copy_tree
package_folder: C:
asset_folder: .
screen resolution: (1920, 1080)
building project: C:
copying python
copying python Lib files
copying always included modules and extra modules
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying always include: C:
copying panda3d
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying: C:
copying ursina
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
compiling: C:
copying assets
ignore: C:
copying assetfolder: C:
ignore: C:
ignore: C:
copying assetfolder: C:
copying asset: C:
copying asset: C:
copying asset: C:
copying asset: C:
copying asset: C:
copying assetfolder: C:
ignore: .py
copying assetfolder: C:
C:
ignore: .py
ignore: .py
ignore: .py
creating .bat file
build complete! time elapsed: 8.46418023109436



Traceback (most recent call last):
  File "c:\source\Vitrix\build.py", line 106, in <module>
    shutil.rmtree(build_path + item)
  File "C:\Users\turus\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 747, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\turus\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 598, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\turus\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 595, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\source\\Vitrix/build/src/test'

c:\source\Vitrix>

```

Above is the output from command prompt, error message being FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\source\\Vitrix/build/src/test'

**Comment by ShadityZ** [comment]
I believe this has to do with the old build system for windows. Linux tests are fine. Check out issue #20. I will send another message when I push the new commit!

**Comment by ShadityZ** [comment]
Issue is fixed now... Let me know if you have any problems

**Comment by Chateauvisionn** [comment]
Please close your issue if it's fixed
